from typing import Protocol

from core.entities.users import User


class UserRepository(Protocol):
    async def add(self, user: User) -> User: ...

    async def update(self, user: User) -> User: ...

    async def delete(self, user_id: str) -> bool: ...

    async def get_by_id(self, user_id: str) -> User | None: ...

    async def get_by_email(self, email: str) -> User | None: ...
